version: 2.0
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    working_directory: ~/clojure-seabattle
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run:
          name: deps
          command: cd ~/clojure-seabattle/seabattle; lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      - run:
          name: tests
          command: cd ~/clojure-seabattle/seabattle; lein test

